#!/bin/sh

pdfname="${1/.pdf}"
tmpdir="${pdfname}-jpgs"
mkdir -p "$tmpdir"
convert -colorspace gray -density 200x200 "$1" "${tmpdir}/img_%04d.jpg" \
    && zip -r "${pdfname}_200dpi.cbz" "$tmpdir" \
    && rm -rf "$tmpdir"
