#!/bin/bash

set -u
set -o pipefail

################################################
# Compile LaTeX documents with nice error/warning/badbox layout
#

if [[ -z "$1" ]]; then
    echo "Usage : pdfLatexPretty file.tex"
    exit 1
fi
if [[ ! -f "$1" ]]; then
    echo "file '$1' does not exist"
    exit 1
fi

export max_print_line=9999999

function ce {
    errors=0
    warnings=0
    badboxes=0
    
    while read line; do
        #color=$(echo $line | cut -d ':' -f1)
        if [[ "$line" =~ [wW]arning[^:]*: ]]; then
            color=3
            ((warnings++))
            line=$(echo "$line" | sed -r 's/^.*(\([^\(]*[wW]arning[^:]*:.*$)/\1/')
        else 
            if [[ "$line" =~ "at line" ]]; then
                color=2
                ((badboxes++))
            else
                if [[ "$line" =~ :[0-9]+: ]]; then
                    color=1
                    ((errors++))
                fi
            fi
        fi
        echo "$(tput setaf $color)$line$(tput sgr0)"
    done

    echo ""
    echo "Errors: $errors"
    echo "Warnings: $warnings"
    echo "Badboxes: $badboxes"
}

function grepLatexErrors {
    grep -E ':[0-9]+:|^l\.[0-9]+|[wW]arning[^:]*:|at line'
    return 0
}

pdflatex -file-line-error -interaction nonstopmode "$1" | grepLatexErrors | ce 

[[ $? == 0 ]] && echo "COMPILATION SUCCESSFUL" || echo "COMPILATION FAILED"
